name: "install uv"
description: "Install uv using the community action"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
